bootstrap.servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=WSEFFYIH7HHKM2TV
sasl.password=cfltblUnEqALeWX0C+GbbL8k+8hyjya+3Ns4GsxfKiRBHSMna4JT9cUm2XdKtPXw